-- Phelps Code Assignment Review
-- Generated by Claude (Anthropic AI)
-- Date: 2025-11-28
--
-- This file contains SQL UPDATE statements to assign Phelps codes to prayers
-- based on manual review and semantic matching between target language prayers
-- and English reference texts.
--
-- Selection criteria:
-- - Semantic similarity between target and English text
-- - Higher confidence scores preferred (>= 40%)
-- - Theme, structure, and key concepts must align
-- - Prayer type (children, fasting, healing, etc.) must match
--

-- ============================================================================
-- LANGUAGE: CY (Welsh/Cy)
-- ============================================================================

-- Prayer UUID: 04bfc0c2-337f-48b6-881d-142f6a98c440
-- Lithuanian text about children as plants, flowers in God's garden
-- Target starts with: "O Dieve! Auklėk šiuos vaikus. Šie vaikai yra Tavo vaisių sodo..."
-- Best match: AB10714 - "O Thou kind Lord! These lovely children are the handiwork..."
-- Theme: Children's prayer, growth and nurturing
-- Confidence: 10%, but semantic match is strong (children theme)
UPDATE writings SET phelps = 'AB10714' WHERE version = '04bfc0c2-337f-48b6-881d-142f6a98c440';
